
//Executive Dashboard Action Types
export const FETCH_EXEC_CHANNEL_SUCCESS = 'FETCH_EXEC_CHANNEL_SUCCESS';
export const FETCH_EXEC_PRODUCT_SUCCESS = 'FETCH_EXEC_PRODUCT_SUCCESS';
export const FETCH_DSA_SUCCESS = 'FETCH_DSA_SUCCESS';
export const FETCH_CUSTOMER_PAY_SUCCESS = 'FETCH_CUSTOMER_PAY_SUCCESS';
export const FETCH_NEW_CUSTOMER_SUCCESS = 'FETCH_NEW_CUSTOMER_SUCCESS';
export const FETCH_CSR_SUCCESS = 'FETCH_CSR_SUCCESS';

 //Sub-Dashboard Action Types
export const FETCH_SUB_CHANNAL_SUCCESS = 'FETCH_SUB_CHANNAL_SUCCESS';
export const FETCH_SUB_PRODUCT_SUCCESS = 'FETCH_SUB_PRODUCT_SUCCESS';
export const FETCH_SUB_DSA_SUCCESS = 'FETCH_SUB_DSA_SUCCESS';
export const FETCH_BDW_SUCCESS = 'FETCH_BDW_SUCCESS';
export const FETCH_MAD_SUCCESS = 'FETCH_MAD_SUCCESS';
export const FETCH_ASI_SUCCESS = 'FETCH_ASI_SUCCESS';

 //Client Data Loader Action Types
export const FETCH_DATA_LOADER_SUCCESS = 'FETCH_DATA_LOADER_SUCCESS';

//Data Browser Action Types
export const FETCH_DATA_BROWSER_SUCCESS = 'FETCH_BROWSER_DATA_SUCCESS';

//Filter Metadata Action Types
export const FETCH_FILTER_METADATA_SUCCESS = 'FETCH_FILTER_METADATA_SUCCESS';
export const FETCH_KEYS_SUCCESS = 'FETCH_KEYS_SUCCESS';