
//Executive Dashboard Action Types
export const FETCH_EXEC_CHANNEL_SUCCESS = 'FETCH_EXEC_CHANNEL_SUCCESS';
export const FETCH_EXEC_PRODUCT_SUCCESS = 'FETCH_EXEC_PRODUCT_SUCCESS';
export const FETCH_DSA_SUCCESS = 'FETCH_DSA_SUCCESS';
export const FETCH_CUSTOMER_PAY_SUCCESS = 'FETCH_CUSTOMER_PAY_SUCCESS';
export const FETCH_NEW_CUSTOMER_SUCCESS = 'FETCH_NEW_CUSTOMER_SUCCESS';

//Sub-Dashboard Action Types
export const FETCH_SUB_CHANNAL_SUCCESS = 'FETCH_SUB_CHANNAL_SUCCESS';
export const FETCH_SUB_PRODUCE_SUCCESS = 'FETCH_SUB_PRODUCE_SUCCESS';
export const FETCH_SUB_DSA_SUCCESS = 'FETCH_SUB_DSA_SUCCESS';
